### PR TITLE
Format the code with pgindent

### PR DESCRIPTION
**Pull request by vitcpp**

### CODE REVIEW

**Comment by esabol** [comment]
I don't really like pgindent's excessive whitespace, but I'm ok with it if this is something you want.

**Comment by vitcpp** [comment]
@esabol I would suggest to consider this PR as a proposal, not a solution to be applied unconditionally. I agree with you about excessive indentation and I'm not a fan pgindent. Furthermore, the formatting of some mathematical expressions should be untouched. But I do not know another solution that may help us with the indentation. We may use pgindent as a code formatting verification tool. We will be able to automate this process. Anyway, I'm ok if we decide to reject this PR and do not use pgindent.

**Comment by esabol** [comment]
I think it’s up to you. I don’t have a strong opinion on it.

**Comment by vitcpp** [comment]
I think it would be better to limit the pgindent functionality somehow. I would propose to fix only identations at the beginnings of the strings, and function signatures. The formatting of formulae should be untouched.

**Comment by vitcpp** [comment]
Rejected, because it is outdated.

**Pull request closed without merging**
