### PR TITLE
Fix output precision limit for double values (issue #118)

### PR DESCRIPTION
**Pull request by vitcpp**
pgSphere used its own setting (set_sphere_output_precision function) to limit the output precision of double values, that could not be greater than 15 significant digits (DBL_DIG). It introduced some problems with dump/restore. PostgreSQL uses its own precision setting: extra_float_digits. The PostgreSQL setting allows to use more significant digits.

This patch changes the default pgSphere output behaviour to utilize PostgreSQL extra_float_digits. Now, extra_float_digits is used by default, until set_sphere_output_precision is called.

The old behaviour is kept for compatibility purposes. Once, set_sphere_output_precision is called, pgSphere starts to use the old behaviour (read, please, issue #118 discussion).

The patch introduces a new function - reset_sphere_output_precision. It is used to reset to the PostgreSQL behaviour after using set_sphere_output_precision.

### CODE REVIEW

**Comment by vitcpp** [comment]
Hi @esabol, once I've changed the default behaviour of the output by improving the precision, some tests show differences in numbers. It is why I've added two new test variants. But, it seems it may be a mistake. It would be better to just replace the old files. I will check. Thank you. BTW, I think to add some a new test for testing output precision with different settings.

**Comment by esabol** [comment]
The changes should definitely have tests. I was just confused as to how the new `expected/*.out` files did that. Variant comparison files are not something I was familiar with. Thank you for the link explaining the concept. If you think this is the best way to implement these tests, I am fine with it.

**Comment by vitcpp** [comment]
expected/epochprop.out differs for 10, 11 and for 12+ versions, because the default precision was 15 significant digits prior to PG12. It is why I've added one more variant comparison file.

image

**Comment by vitcpp** [comment]
> Why not put `set extra_float_digits = 2;` at the top of each "general" test file, and only check for the varying precision in a specific test for that purpose, if at all? (Ok, I see it's only the gist bounding box test that's affected, but that seems unrelated functionality.)

It makes sense, thank you! It seems, set_sphere_output_precision(8) is set at the top of almost all tests.

**Review by esabol — APPROVED** [review]
Looks good! Thank you!

**Comment by vitcpp** [comment]
I've added one more commit to set extra_float_digits = 2 for epochprop and bounding_box_gist tests. It allows to remove expexted/bounding_box_gist_2.out but expected/epochprop_1.out is still required. The reason to create expected/epochprop_1.out is that the earlier versions output exactly 17 digits if extra_float_digits is 2, some of these digits meaningless. PG versions 12+ use a special function that outputs only meaningful digits even if extra_float-digits = 2, it is why in PG 12+ some numbers may contain less than 17 digits if the text representation if enough to define the double number.

**Review by esabol — APPROVED** [review]
Looks better!

**Pull request merged**
